"""Giao diện demo Lab 17 — Multi-Memory Agent với Zep.

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

The page shell, budget metrics, evidence inspection, and Gemini chat are wired
into one presentation-friendly retrieval flow.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.context_budget import ContextBudgetManager
from src.llm import generate_reply, llm_available, llm_provider
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CASE_GUIDES = {
    "E01": {
        "title": "Nhớ hội thoại hiện tại",
        "question": "Thông tin vừa xuất hiện trong thread là gì?",
        "answer": "ORCHID-27",
        "say": "Short-term memory đọc các turn gần nhất trong phiên hiện tại.",
    },
    "E02": {
        "title": "Nhớ preference xuyên session",
        "question": "Minh ưu tiên ngôn ngữ lập trình nào cho demo cá nhân?",
        "answer": "Python",
        "say": "Long-term memory lấy preference từ Zep Context Block, dù thông tin không nằm trong thread hiện tại.",
    },
    "E03": {
        "title": "Nhớ task chưa hoàn thành",
        "question": "Minh còn deadline hoặc open loop nào?",
        "answer": "benchmark report · 16:00",
        "say": "Long-term memory giữ durable task và deadline.",
    },
    "E04": {
        "title": "Nhớ một incident cũ",
        "question": "Minh đã xử lý async HTTP timeout như thế nào?",
        "answer": "ClientSession · concurrency=20 · ASYNC-FIX-20",
        "say": "Episodic memory tìm lại trajectory cụ thể của một sự kiện trước đây.",
    },
    "E05": {
        "title": "Nhớ reflection của incident",
        "question": "Root cause có phải chỉ là tăng timeout không?",
        "answer": "connection churn · timeout threshold",
        "say": "Episodic memory giữ cả reflection và bài học sau sự kiện.",
    },
    "E06": {
        "title": "Tìm policy domain dùng chung",
        "question": "Quy tắc retry POST payment là gì?",
        "answer": "Idempotency-Key · max-3-retries · exponential-backoff",
        "say": "Semantic memory tìm trong standalone graph, không phụ thuộc user cụ thể.",
    },
    "E07": {
        "title": "Kết hợp memory cá nhân và domain",
        "question": "Chọn hướng dẫn retry payment phù hợp với Minh.",
        "answer": "Python + Idempotency-Key",
        "say": "Mixed retrieval ghép preference cá nhân với policy payment dùng chung.",
    },
}

CSS = """
<style>
.block-container { padding-top: 2rem; max-width: 1200px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:14px 16px; margin-bottom:12px; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    guide = CASE_GUIDES.get(case["id"], {})
    return f"{case['id']} · {guide.get('title', case['expected_layer'])}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Run student retrieval for the loaded case.

    Return a dict with keys:
      - "merged_context": str  (StudentMemory.assemble_context output)
      - "layers": dict[str, str]  (per-layer evidence: short_term/long_term/
                                   episodic/semantic)
      - "budget": dict  (the breakdown from assemble_context)

    Hints:
      * Build short_term from case["fixture_messages"] if present, else from
        the matching user/thread messages in data/sessions.json, plus
        extra_messages. E01 has no fixture — it uses thread minh-s1.
      * Decide which durable layers to fetch from case["expected_layer"] (or
        case["retrieve_layers"] for "mixed"), then call
        memory.retrieve_long_term / retrieve_episodic / retrieve_semantic.
      * Keep user_id and thread_id from the loaded case.
      * Finish with memory.assemble_context(layers).
    """
    dataset = load_dataset()
    layers: dict[str, str] = {
        "short_term": "",
        "long_term": "",
        "episodic": "",
        "semantic": "",
    }
    messages = list(case.get("fixture_messages") or [])
    if not messages:
        for user in dataset.get("users", []):
            if user.get("user_id") != case.get("user_id"):
                continue
            for session in user.get("sessions", []):
                if session.get("thread_id") == case.get("thread_id"):
                    messages = list(session.get("messages") or [])
                    break
            break

    short_term = ShortTermMemory(
        strategy="sliding", max_recent_messages=6, pressure_tokens=450
    )
    for message in messages:
        short_term.add(message.get("role", "user"), message.get("content", ""))
    for message in extra_messages:
        short_term.add(message.get("role", "user"), message.get("content", ""))

    expected_layer = case.get("expected_layer")
    wanted = case.get("retrieve_layers") or [expected_layer]
    if expected_layer == "mixed" and not case.get("retrieve_layers"):
        wanted = ["long_term", "semantic"]

    user_id = case.get("user_id", "")
    thread_id = case.get("thread_id", "")
    query = case.get("query", "")
    if "short_term" in wanted:
        layers["short_term"] = short_term.render()
    if "long_term" in wanted:
        layers["long_term"] = memory.retrieve_long_term(user_id, thread_id, query)
    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)
    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged_context, budget = memory.assemble_context(layers)
    return {
        "merged_context": merged_context,
        "layers": layers,
        "budget": budget,
        "short_term_stats": short_term.stats(),
        "requested_layers": wanted,
    }


def retrieve_from_saved_report(case: dict[str, Any], extra_messages: list[dict[str, str]]) -> dict[str, Any]:
    """Offline presentation fallback when Zep Cloud is unavailable.

    It replays the already-scored student benchmark evidence. This keeps the
    UI demo usable without pretending that a live Zep retrieval succeeded.
    """
    report_path = _ROOT / "reports" / "benchmark.json"
    if not report_path.exists():
        raise RuntimeError("Không có reports/benchmark.json để chạy demo offline.")
    report = load_json(report_path)
    result = next((item for item in report.get("results", []) if item.get("id") == case.get("id")), None)
    if not result:
        raise RuntimeError(f"Không tìm thấy evidence đã lưu cho case {case.get('id')}.")

    layers = {"short_term": "", "long_term": "", "episodic": "", "semantic": ""}
    layer = result.get("layer", case.get("expected_layer", ""))
    retrieved = result.get("retrieved", "") or ""
    if layer in layers:
        layers[layer] = retrieved
    elif layer == "mixed":
        for name in ("long_term", "semantic"):
            start, end = f"<{name.upper()}>", f"</{name.upper()}>"
            if start in retrieved and end in retrieved:
                layers[name] = retrieved.split(start, 1)[1].split(end, 1)[0].strip()

    merged, budget = ContextBudgetManager(settings.context_tokens).assemble(layers)
    return {
        "merged_context": merged,
        "layers": layers,
        "budget": budget,
        "short_term_stats": result.get("short_term_stats", {}),
        "requested_layers": [layer],
        "offline": True,
    }


def main() -> None:
    st.set_page_config(page_title="Lab 17 · Memory Agent", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 · Multi-Memory Agent")
    st.caption("Quan sát agent tìm đúng ký ức, ghép context và trả lời có căn cứ.")

    with st.sidebar:
        st.header("Thiết lập")
        zep_ok = bool(settings.zep_api_key) and settings.zep_api_key != "__USER_PROVIDED_KEY__"
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep "
                    + ("đã kết nối" if zep_ok else "chưa có API key"))
        st.markdown(("✅" if llm_available() else "⚠️") + " Chat model "
                    + (f"đã sẵn sàng" if llm_available() else "chưa cấu hình"))
        st.caption(f"Nhà cung cấp: `{llm_provider()}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Chọn tình huống demo", labels)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'<div class="lab-card">{layer_badge(case.get("expected_layer","?"))}'
        f'<b>{case["id"]}</b><br>'
        f'<span class="lab-kv"><b>Người dùng:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p style="margin:.5rem 0 0">{case.get("query","")}</p>'
        f'<span class="lab-kv">{case.get("description","")}</span></div>',
        unsafe_allow_html=True,
    )

    guide = CASE_GUIDES.get(case["id"], {})
    if guide:
        st.markdown("### 🧭 Case này đang kiểm tra gì?")
        guide_cols = st.columns([1, 1, 1.4])
        guide_cols[0].markdown(f"**Câu hỏi**\n\n{guide['question']}")
        guide_cols[1].markdown(f"**Câu trả lời cần thấy**\n\n`{guide['answer']}`")
        guide_cols[2].markdown(f"**Cách giải thích**\n\n{guide['say']}")

    required = case.get("must_contain_all") or []
    if required:
        chips = " ".join(f'<span class="evidence-chip">{marker}</span>' for marker in required)
        st.markdown(f"**Bằng chứng cần tìm để PASS**  {chips}", unsafe_allow_html=True)
    st.markdown(
        '<div class="explain-note"><b>Cách đọc demo:</b> agent chỉ gọi các memory layer liên quan, sau đó ghép và cắt context theo thứ tự short-term → long-term → episodic → semantic.</div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    col_run, _ = st.columns([1, 3])
    if col_run.button("▶ Chạy truy hồi cho tình huống này", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.warning(
                "Zep Cloud chưa xác thực được (401 hoặc API key chưa hợp lệ). "
                "Đang chuyển sang demo offline bằng evidence benchmark đã lưu."
            )
            try:
                st.session_state.last_result = retrieve_from_saved_report(case, st.session_state.chat)
            except Exception:
                st.error(f"Không thể chạy demo: {exc}")

    result = st.session_state.get("last_result")
    if result:
        if result.get("offline"):
            st.info("Chế độ demo offline: đang phát lại evidence từ reports/benchmark.json; chưa gọi Zep live.")
        st.markdown("### 🔎 Kết quả truy hồi")
        retrieved_all = "\n".join(result["layers"].values()).casefold()
        missing = [marker for marker in required if marker.casefold() not in retrieved_all]
        if missing:
            st.warning("Chưa thấy đủ bằng chứng: " + ", ".join(missing))
        else:
            st.success(f"PASS: đã tìm thấy đủ {len(required)} marker cần thiết.")
        active = [k for k, v in result["layers"].items() if v.strip()]
        st.markdown(" ".join(layer_badge(k) for k in active) or "_(nothing retrieved)_",
                    unsafe_allow_html=True)

        if result.get("budget"):
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                b = result["budget"].get(layer, {})
                cols[i].metric(
                    layer,
                    f"{b.get('used_tokens', 0)} tok",
                    help=f"giới hạn {b.get('limit_tokens', 0)} · ban đầu {b.get('raw_tokens', 0)}",
                )

        with st.expander("Context kỹ thuật cuối cùng đưa vào agent · mở khi cần giải thích sâu", expanded=False):
            st.code(result.get("merged_context") or "(trống)", language="markdown")
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f"Bằng chứng kỹ thuật · {name}", expanded=False):
                    st.write(text)

    st.markdown("### 💬 Chat tiếp với memory")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Nhập câu hỏi để agent nhớ và trả lời…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if llm_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(Chưa cấu hình model chat — đang hiển thị context truy hồi)_\n\n"
                         + (context[:1500] or "(chưa truy hồi được memory)"))
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception:
            follow = retrieve_from_saved_report(case, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            reply = generate_reply(context, st.session_state.chat[:-1], prompt) if llm_available() else context[:1500]
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)


if __name__ == "__main__":
    main()
